services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - go-network

  mysql:
    image: 'mysql/mysql-server:8.0'
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
      - ./src/database/init:/docker-entrypoint-initdb.d
    networks:
      - go-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: 5s

  go-app:
    build: .
    image: go-app
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/go-app
    restart: on-failure
    env_file:
      - .env
    networks:
      - go-network
volumes:
  dbdata:

networks:
  go-network:
    driver: bridge
